### ISSUE TITLE
pip install aimsim[mordred] not working on Mac

### ISSUE THREAD

**Issue by GattiMh** [VlachosGroup/AIMSim#251]
Hello,

I have installed aimsim using the classic pip install command and it manages to install it but when I tried adding the [mordred] extra as explained in the documentation, I get:

`pip install aimsim[mordred]
zsh: no matches found: aimsim[mordred]`

Os is on intel Mac btw, any suggestions?
Working on a new conda env with python=3.8

Many thanks

**Comment by JacksonBurns** [comment]
HI @GattiMh thanks for the issue!

I believe that, since you are using `zsh` , you will need to change the install to `pip install 'aimsim[mordred]'` since the bracket is reserved in `zsh`.

I have just updated the README with this additional info -- thanks for bringing this to our attention.

**Comment by GattiMh** [comment]
Thanks! Now the installation works but when I try to run it using:

`aimsim`

I get:

`Traceback (most recent call last):
  File "/Users/opt/miniconda3/envs/aimsim/bin/aimsim", line 5, in <module>
    from aimsim.__main__ import start_AIMSim
  File "/Users/opt/miniconda3/envs/aimsim/lib/python3.8/site-packages/aimsim/__init__.py", line 1, in <module>
    from . import ops
  File "/Users/opt/miniconda3/envs/aimsim/lib/python3.8/site-packages/aimsim/ops/__init__.py", line 1, in <module>
    from .descriptor import Descriptor
  File "/Users/opt/miniconda3/envs/aimsim/lib/python3.8/site-packages/aimsim/ops/descriptor.py", line 23, in <module>
    class Descriptor:
  File "/Users/opt/miniconda3/envs/aimsim/lib/python3.8/site-packages/aimsim/ops/descriptor.py", line 169, in Descriptor
    def _set_mordred_descriptor(self, molecule_graph, descriptor, **kwargs):
  File "/Users/opt/miniconda3/envs/aimsim/lib/python3.8/site-packages/aimsim/utils/extras.py", line 10, in requires_mordred
    return function()
TypeError: _set_mordred_descriptor() missing 3 required positional arguments: 'self', 'molecule_graph', and 'descriptor'`

**Comment by JacksonBurns** [comment]
Hi again @GattiMh sorry for the delay -- I have tried on a few different machines and shells now and I am unable to reproduce this error locally.

Can you try running the install like this: `pip install --force-reinstall --no-cache-dir 'aimsim[mordred]'`? This will ensure that you have the latest release of `AIMSim` as well as the appropriate dependency versions.

If this does not work and you are in a conda virtual environment, can you make a new one as well for the install?

If none of that works, please reply to this with the output of `pip list`

**Comment by GattiMh** [comment]
Thanks Jackson, now it seems that I can open the GUI. I used the reinstall command as you've shown
